name: Test and deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm 
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          n=0
          until [ "$n" -ge 5 ]
          do
            pnpm install --frozen-lockfile && break
            n=$((n+1))
            echo "Retrying in 5 seconds..."
            sleep 5
          done
      
      - name: tsc paint worklet
        run: npm run worklet

      - name: Run tests
        run: npm run test

  build:
    name: Build docs
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          n=0
          until [ "$n" -ge 5 ]
          do
            pnpm install --frozen-lockfile && break
            n=$((n+1))
            echo "Retrying in 5 seconds..."
            sleep 5
          done

      - name: Build Components
        run: npm run build

      - name: Build docs
        run: npm run docs:build

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./packages/docs/.vitepress/dist  # 路径修正

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download docs
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # 路径修正
          allow_empty_commit: false
          keep_files: true